image_size = 33
label_size = 21
batch_size = 128
c_dim = 1
stride = 21
scale =3
checkpoint_dir = "C:\\Users\\zzy\\Desktop\\learn\\checkpoint"
epoch = 2000
sample_dir = "C:\\Users\\zzy\\Desktop\\learn\\sample"
learning_rate = 1e-2